# Nixpacks configuration for Railway
providers = ["node"]

[variables]
NODE_VERSION = "18"

[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
    "npm install",
    "cd client && npm install && cd .."
]

[phases.build]
cmds = [
    "npm run build", 
    "cd client && npm run build && cd .."
]

[start]
cmd = "node dist/index.js"